server:
  port: 8088

spring:
  datasource:                                           # 数据源的相关配置
    url: jdbc:mysql://rm-bp112prh49m0mj1v54o.mysql.rds.aliyuncs.com:3306/edu-center-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: chenchuxiang
    password: Chenchu2580

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

file:
  upload-address: D:\data\edu-center\
  show:
    prefix: www.bangmom.top/images/